//
//===========================================================================================
//
//	This file is automatically generated by SetBld (x86 Unicode).
//
//	(c) 2003 - 2024 Macallan - mailto:ian.macallan@gmail.com
//
//	Generated : 28/05/2024 10:34:18
//
//===========================================================================================
//
#pragma once

#ifdef UNICODE
#define PROGRAM_MAIL    L"mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    L"https://www.macallan.org/"
#define PROGRAM_DWNL    L"https://home.macallan.org:9443/"
#define PROGRAM_WIKI    L"https://www.macallan.org/"
#define PROGRAM_FORUM   L"https://www.macallan.org/"
#define PROGRAM_MMSFAQ  L"https://www.macallan.org/"
#define PROGRAM_RSS     L"index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    L"news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    L"www.macallan.org"
#define PROGRAM_NAME    L"wsrm"
#ifdef _WIN64
#define PROGRAM_NAME_P  L"wsrm (x64 Unicode)"
#else
#define PROGRAM_NAME_P  L"wsrm (x86 Unicode)"
#endif
#define PROGRAM_SECT    L"wsrm"
#define PROGRAM_REGKEY  L"Macallan\\wsrm"
#define PROGRAM_SOFTKEY L"SOFTWARE\\Macallan\\wsrm"
#define PROGRAM_CHARS   L"Unicode"
#else
#define PROGRAM_MAIL    "mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    "https://www.macallan.org/"
#define PROGRAM_DWNL    "https://home.macallan.org:9443/"
#define PROGRAM_WIKI    "https://www.macallan.org/"
#define PROGRAM_FORUM   "https://www.macallan.org/"
#define PROGRAM_MMSFAQ  "https://www.macallan.org/"
#define PROGRAM_RSS     "index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    "news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    "www.macallan.org"
#define PROGRAM_NAME    "wsrm"
#ifdef _WIN64
#define PROGRAM_NAME_P  "wsrm (x64 MBCS)"
#else
#define PROGRAM_NAME_P  "wsrm (x86 MBCS)"
#endif
#define PROGRAM_SECT    "wsrm"
#define PROGRAM_REGKEY  "Macallan\\wsrm"
#define PROGRAM_SOFTKEY "SOFTWARE\\Macallan\\wsrm"
#define PROGRAM_CHARS   "MBCS"
#endif

#ifdef UNICODE
#define PROGRAM_DATE    L"Tue May 28 10:34"
#define PROGRAM_DATE_F  L"Tue May 28 10:34 2024"
#define PROGRAM_YEAR    L"2024"
#define PROGRAM_TIME    L"2024/05/28 10:34:18"
#else
#define PROGRAM_DATE    "Tue May 28 10:34"
#define PROGRAM_DATE_F  "Tue May 28 10:34 2024"
#define PROGRAM_YEAR    "2024"
#define PROGRAM_TIME    "2024/05/28 10:34:18"
#endif

#ifdef UNICODE
#define PROGRAM_VERSION L"1.0.15.006"
#define PROGRAM_INSTALL L"1.0.15006"
#define PROGRAM_VER_NUM 10015006
#define PROGRAM_BUILD   L"190"
#define PROGRAM_TITLE   L"wsrm"
#ifdef _WIN64
#define PROGRAM_TITLE_P L"wsrm (x64 Unicode)"
#else
#define PROGRAM_TITLE_P L"wsrm (x86 Unicode)"
#endif
#else
#define PROGRAM_VERSION "1.0.15.006"
#define PROGRAM_INSTALL "1.0.15006"
#define PROGRAM_VER_NUM 10015006
#define PROGRAM_BUILD   "190"
#define PROGRAM_TITLE   "wsrm"
#ifdef _WIN64
#define PROGRAM_TITLE_P "wsrm (x64 MBCS)"
#else
#define PROGRAM_TITLE_P "wsrm (x86 MBCS)"
#endif
#endif

