//
//===========================================================================================
//
//	This file is automatically generated by SetBld (x86 Unicode).
//
//	(c) 2003 - 2025 Macallan - mailto:ian.macallan@gmail.com
//
//	Generated : 13/11/2025 10:04:07
//
//===========================================================================================
//
#pragma once

#ifndef AUTOMATICVERSIONHEADER_H
#define AUTOMATICVERSIONHEADER_H    1

#ifdef UNICODE
#define PROGRAM_MAIL    L"mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    L"https://www.macallan.org/"
#define PROGRAM_DWNL    L"https://home.macallan.org:9443/"
#define PROGRAM_WIKI    L"https://www.macallan.org/"
#define PROGRAM_FORUM   L"https://www.macallan.org/"
#define PROGRAM_MMSFAQ  L"https://www.macallan.org/"
#define PROGRAM_RSS     L"index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    L"news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    L"www.macallan.org"
#define PROGRAM_NAME    L"wsrm"
#ifdef _WIN64
#define PROGRAM_NAME_P  L"wsrm (x64 Unicode)"
#else
#define PROGRAM_NAME_P  L"wsrm (x86 Unicode)"
#endif
#define PROGRAM_SECT    L"wsrm"
#define PROGRAM_REGKEY  L"Macallan\\wsrm"
#define PROGRAM_SOFTKEY L"SOFTWARE\\Macallan\\wsrm"
#define PROGRAM_CHARS   L"Unicode"
#else
#define PROGRAM_MAIL    "mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    "https://www.macallan.org/"
#define PROGRAM_DWNL    "https://home.macallan.org:9443/"
#define PROGRAM_WIKI    "https://www.macallan.org/"
#define PROGRAM_FORUM   "https://www.macallan.org/"
#define PROGRAM_MMSFAQ  "https://www.macallan.org/"
#define PROGRAM_RSS     "index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    "news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    "www.macallan.org"
#define PROGRAM_NAME    "wsrm"
#ifdef _WIN64
#define PROGRAM_NAME_P  "wsrm (x64 MBCS)"
#else
#define PROGRAM_NAME_P  "wsrm (x86 MBCS)"
#endif
#define PROGRAM_SECT    "wsrm"
#define PROGRAM_REGKEY  "Macallan\\wsrm"
#define PROGRAM_SOFTKEY "SOFTWARE\\Macallan\\wsrm"
#define PROGRAM_CHARS   "MBCS"
#endif

#ifdef UNICODE
#define PROGRAM_DATE    L"Thu Nov 13 10:04"
#define PROGRAM_DATE_F  L"Thu Nov 13 10:04 2025"
#define PROGRAM_YEAR    L"2025"
#define PROGRAM_TIME    L"2025/11/13 10:04:07"
#else
#define PROGRAM_DATE    "Thu Nov 13 10:04"
#define PROGRAM_DATE_F  "Thu Nov 13 10:04 2025"
#define PROGRAM_YEAR    "2025"
#define PROGRAM_TIME    "2025/11/13 10:04:07"
#endif

#ifdef UNICODE
#define PROGRAM_VERSION L"1.0.15.018"
#define PROGRAM_INSTALL L"1.0.15018"
#define PROGRAM_VER_NUM 10015018
#define PROGRAM_BUILD   L"202"
#define PROGRAM_TITLE   L"wsrm"
#ifdef _WIN64
#define PROGRAM_TITLE_P L"wsrm (x64 Unicode)"
#else
#define PROGRAM_TITLE_P L"wsrm (x86 Unicode)"
#endif
#else
#define PROGRAM_VERSION "1.0.15.018"
#define PROGRAM_INSTALL "1.0.15018"
#define PROGRAM_VER_NUM 10015018
#define PROGRAM_BUILD   "202"
#define PROGRAM_TITLE   "wsrm"
#ifdef _WIN64
#define PROGRAM_TITLE_P "wsrm (x64 MBCS)"
#else
#define PROGRAM_TITLE_P "wsrm (x86 MBCS)"
#endif
#endif

#endif

